// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/DiffHalves2.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class DiffHalves2 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=16;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,DiffHalves2.createAutomaton()));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,DiffHalves2.class,"main",$line);
    }
  }
  public static IPushdownAutomaton createAutomaton() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=19;
      Object \u03A3=$fix($opIntvlY('a','b'));
      $line=21;
      Object Q=$fix($opUnionY(GCollections.asSet('I','F'),\u03A3));
      $line=23;
      Object \u0393=$fix(GCollections.asSet('0','1'));
      $line=24;
      Object q_0=$fix('I');
      $line=25;
      Object F=$fix(GCollections.asSet('F'));
      $line=26;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=28;
      for (Object $v1:GCollections.unmodifiableCollection(\u03A3)) {
        Object \u03C3=$v1;
        $line=30;
        $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta('I','I',$cast(java.lang.String.class,\u03C3)),new Object[]{"0"});
        $line=31;
        $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta('I',\u03C3,$cast(java.lang.String.class,\u03C3)),new Object[]{});
        $line=32;
        $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta('F','F',$cast(java.lang.String.class,\u03C3)),new Object[]{"1"});
        $line=34;
        for (Object $v2:GCollections.unmodifiableCollection(\u03A3)) {
          Object x=$v2;
          $line=35;
          $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(x,x,$cast(java.lang.String.class,\u03C3)),new Object[]{"0"});
          $line=36;
          $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(x,x,$cast(java.lang.String.class,\u03C3)),new Object[]{"1"});
          $line=37;
          if ($bool(!$opEqualY(x,\u03C3))) {
            $line=38;
            $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(x,'F',$cast(java.lang.String.class,\u03C3)),new Object[]{});
          }
        }
      }
      $line=43;
      $result=M;
      if (true) break $try;
      $line=44;
      $rethrow(new RuntimeException("The function \"createAutomaton()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,DiffHalves2.class,"createAutomaton",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
}
